### ISSUE TITLE
unity add the javasource and use openLiveWallpaperService method but crash 

### ISSUE THREAD

**Issue by renzhe2015** [JustinFincher/UniLWP.Droid.Free.JavaSource#1]
unity add the javasource aar  and use openLiveWallpaperService method to set the wallpaper ,but the wallpaper will recover the system default wallpaper ,i do not konw why

**Comment by JustinFincher** [comment]
Hi! Thanks for reporting this, could you please elaborate more about this? Do you mean the wallpaper preview simply does not work when pressing the 'set' button?

**Comment by JustinFincher** [comment]
Also, it would be much appreciated if you can provide your Android version (including custom skin name) and device number, thanks! @renzhe2015

**Comment by renzhe2015** [comment]
yes ，i clicked the set button  and the 3d wallpaper worked about 2 minutes and it would back to the default system wallpaper, my phone is android Q

**Comment by renzhe2015** [comment]
the unity version is 2019.3.14f1

**Comment by JustinFincher** [comment]
That’s weird, normally when this happens it means the app has crashed and therefore the service is force stopped along with the app itself. Can you please provide adb logs? They can be accessed via either adb command or Unity logcat package.
BTW, what phone is it?

**Comment by renzhe2015** [comment]
i test the unity apk in OPPO phone, but i test your demo.apk, it will not change to system wallpaper , so i want to konw if there is some differents between the java soure aar and the demo apk 's aar

**Comment by renzhe2015** [comment]
on the other hand, i add button in unity scene and add click listener to the button ,but the listener does not work any more

**Comment by JustinFincher** [comment]
Sorry for the late reply, I was traveling yesterday so I really haven't got much time checking emails.
OPPO phones should be fine, but I cannot say it for sure. There are indeed differences between the aar on GitHub and the aar in demo apk, but they are mostly minor changes which I doubt will cause the crash. Maybe you can provide a crash log via adb so that I can locate where the bug exactly is?
As for the button, this is the designated behavior, as the open-sourced version does not offer such touch event forwarding implementation, and thus the event manager simply does not work. However, they are relatively easy to add on your own (just follow the default exported Activity in Unity Android module), or you can email me privately so I can offer you a code for the full-fledged version on Asset Store, which contains the touch event feature. You can also reach out to me via WeChat (JustZht), QQ, Telegram, or other means listed on [my website](https://fincher.im).

**Comment by renzhe2015** [comment]
thanks your reply, i have sended email to you

**Comment by JustinFincher** [comment]
@renzhe2015 Just want to let you know that I have replied back to you, please check the mail for details (a voucher code included), thank you

**Comment by renzhe2015** [comment]
i have sloved the problem , it should add ovride method lowmemory in the engine, thanks

**Comment by JustinFincher** [comment]
@renzhe2015 Did the override exist in the paid version I sent you? If that is the case then I will add this fix to the free version as well, thanks for reporting!
